spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: jgc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.main.bean

server:
  port: 8090